name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=v1.0.${{ github.run_number }}
        gh release create $TAG_NAME target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip --title "Release $TAG_NAME" --notes "Automated release from GitHub Actions"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: parsi-analyzer-zip
        path: target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
